"""Argument parser for the Gev porcelain and plumbing commands."""

from __future__ import annotations

import argparse


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="gev")
    commands = parser.add_subparsers(dest="command", required=True)

    study = commands.add_parser("study", help="plan or run a reproducible multi-seed study")
    study_commands = study.add_subparsers(dest="study_action", required=True)
    study_plan = study_commands.add_parser("plan", help="read-only plan; no weights are loaded")
    study_plan.add_argument("config"); study_plan.add_argument("--data", default="data")
    study_plan.add_argument("--seeds", default="0,1,2")
    study_run = study_commands.add_parser("run", help="run a planned multi-seed study")
    study_run.add_argument("config"); study_run.add_argument("--out", required=True)
    study_run.add_argument("--data", default="data"); study_run.add_argument("--seeds", default="0,1,2")
    study_run.add_argument("--max-steps", type=int); study_run.add_argument("--smoke", action="store_true")
    study_run.add_argument("--existing-run")

    train_cmd = commands.add_parser("train", help="train from a config; --resume restores optimizer, --init-from warm-starts")
    train_cmd.add_argument("config"); train_cmd.add_argument("--data", default="data")
    train_cmd.add_argument("--out", required=True); train_cmd.add_argument("--max-steps", type=int)
    train_cmd.add_argument("--device", choices=("cpu", "mps"))
    initialization = train_cmd.add_mutually_exclusive_group()
    initialization.add_argument("--resume", help="resume full optimizer/scheduler/RNG state at a saved boundary")
    initialization.add_argument("--init-from", help="initialize weights from a run with a fresh optimizer")

    evaluate = commands.add_parser("evaluate", help="evaluate a checkpoint on a non-test split")
    evaluate.add_argument("run"); evaluate.add_argument("--config")
    evaluate.add_argument("--suite", required=True, choices=("decision-v7", "transfer-v4"))
    evaluate.add_argument("--split", required=True, choices=("development", "calibration"))
    evaluate.add_argument("--data", default="data"); evaluate.add_argument("--out", required=True)
    evaluate.add_argument("--temperature", type=float); evaluate.add_argument("--device", choices=("cpu", "mps"))
    evaluate.add_argument("--execution", choices=("rows", "packed"))

    predict = commands.add_parser("predict", help="predict an unlabeled Kev-style request")
    predict.add_argument("run", help="current-format checkpoint run or checkpoint directory")
    predict.add_argument("--config", help="override the saved checkpoint configuration")
    predict.add_argument("--input", required=True, help="JSON request file or '-' for stdin")
    predict.add_argument("--temperature", type=float, default=1.0, help="inference temperature (default: raw T=1)")
    predict.add_argument("--device", choices=("cpu", "mps"))

    calibrate = commands.add_parser("calibrate", help="fit a protocol-approved temperature from saved rows")
    calibrate.add_argument("--run", required=True); calibrate.add_argument("--rows")
    calibrate.add_argument("--protocol", choices=("kev-screening", "kev-release"), default="kev-screening")
    calibrate.add_argument("--out", required=True); calibrate.add_argument("--update-checkpoint", action="store_true")

    compare = commands.add_parser("compare", help="paired-bootstrap two saved evaluations")
    compare.add_argument("--candidate", required=True); compare.add_argument("--reference", required=True)
    compare.add_argument("--aggregation", choices=("micro", "macro"), default="micro")
    compare.add_argument("--samples", type=int, default=1000); compare.add_argument("--seed", type=int, default=0)
    compare.add_argument("--out", required=True); compare.add_argument("--calibrated", action="store_true")
    compare.add_argument("--allow-test-compare", action="store_true")

    data = commands.add_parser("data", help="fetch, verify, audit, sample, or prepare reproducible data")
    data_commands = data.add_subparsers(dest="data_action", required=True)
    fetch = data_commands.add_parser("fetch")
    fetch.add_argument("target", choices=("decision-v7", "transfer-v4", "night2"))
    fetch.add_argument("split", nargs="?", choices=("train", "calibration", "development"))
    fetch.add_argument("--data-root", default="data")
    verify = data_commands.add_parser("verify")
    verify.add_argument("suite", choices=("decision-v7", "transfer-v4"))
    verify.add_argument("split", choices=("train", "calibration", "development")); verify.add_argument("path")
    audit = data_commands.add_parser("audit")
    audit.add_argument("target", choices=("decision-v7", "transfer-v4", "tokens"))
    audit.add_argument("split", nargs="?", choices=("train", "calibration", "development"))
    audit.add_argument("path", nargs="?"); audit.add_argument("--data-root", default="data")
    audit.add_argument("--config"); audit.add_argument("--markers"); audit.add_argument("--augment", action="store_true")
    audit.add_argument("--seeds", default="0,1,2"); audit.add_argument("--out", default="runs/reference/token-length-audit.json")
    sample = data_commands.add_parser("sample", help="write a group-preserving smoke child suite")
    sample.add_argument("--data-root", default="data"); sample.add_argument("--out", default="data/smoke")
    sample.add_argument("--train-records", type=int, default=128); sample.add_argument("--dev-records", type=int, default=64)
    sample.add_argument("--seed", type=int, default=0)
    prepare = data_commands.add_parser("prepare", help="prepare a derived training dataset")
    prepare.add_argument("target", choices=("night2",)); prepare.add_argument("--data-root", default="data")
    prepare.add_argument("--out", required=True)

    locked = commands.add_parser("locked", help="explicit once-only held-out test workflows")
    locked_commands = locked.add_subparsers(dest="locked_action", required=True)
    register = locked_commands.add_parser("register", help="pre-register a verified production candidate")
    register.add_argument("--run", required=True); register.add_argument("--study", required=True); register.add_argument("--out", required=True)
    locked_evaluate = locked_commands.add_parser("evaluate", help="reserve and evaluate held-out test once")
    locked_evaluate.add_argument("--run", required=True); locked_evaluate.add_argument("--selection", required=True)
    locked_evaluate.add_argument("--suites", default="decision-v7,transfer-v4"); locked_evaluate.add_argument("--data", default="data")
    locked_evaluate.add_argument("--out", required=True); locked_evaluate.add_argument("--ledger", default="runs/locked-ledger.jsonl")
    locked_evaluate.add_argument("--config"); locked_evaluate.add_argument("--device", choices=("cpu", "mps"))

    diagnose = commands.add_parser("diagnose", help="diagnostic and validation workflows")
    diagnose_commands = diagnose.add_subparsers(dest="diagnose_action", required=True)
    diagnose_config = diagnose_commands.add_parser("config", help="validate a frozen experiment configuration")
    diagnose_config.add_argument("config")
    diagnose_commands.add_parser("environment", help="run actual CPU/MPS runtime diagnostics")
    diagnose_model = diagnose_commands.add_parser("model", help="inspect a model or run its row-model diagnostic")
    model_mode = diagnose_model.add_mutually_exclusive_group()
    model_mode.add_argument("--tiny", action="store_true", help="run a random tiny model diagnostic")
    model_mode.add_argument("--probe", action="store_true", help="load and probe the configured real model")
    diagnose_model.add_argument("--config")
    diagnose_model.add_argument("--device", choices=("cpu", "mps")); diagnose_model.add_argument("--output-root")
    diagnose_train = diagnose_commands.add_parser("train", help="profile a bounded real training window")
    diagnose_train.add_argument("--config", default="configs/gemma3-1b-mps-fast.toml"); diagnose_train.add_argument("--data", default="data")
    diagnose_train.add_argument("--warmup-steps", type=int, default=2); diagnose_train.add_argument("--measure-steps", type=int, default=4); diagnose_train.add_argument("--out", required=True)
    diagnose_precision = diagnose_commands.add_parser("precision", help="run bounded precision agreement checks")
    diagnose_precision.add_argument("--run", required=True); diagnose_precision.add_argument("--config", default="configs/gemma3-1b-v7.toml")
    diagnose_precision.add_argument("--records", type=int, default=16); diagnose_precision.add_argument("--data", default="data"); diagnose_precision.add_argument("--out", required=True)
    diagnose_execution = diagnose_commands.add_parser("execution", help="measure rows versus packed development execution")
    diagnose_execution.add_argument("--run", required=True); diagnose_execution.add_argument("--config", default="configs/gemma3-1b-v7.toml")
    diagnose_execution.add_argument("--records", type=int, default=8); diagnose_execution.add_argument("--device", choices=("cpu", "mps"))
    diagnose_execution.add_argument("--data", default="data"); diagnose_execution.add_argument("--out", required=True)
    return parser
